electric_zoo = Concert.create(title: 'Electric Zoo')
ultra = Concert.create(title: 'Ultra Music Festival')
afropunk = Concert.create(title: 'AFROPUNK FEST')
electric_daisy = Concert.create(title: 'Electric Daisy Carnival Las Vegas')
bonnaroo = Concert.create(title: 'Bonnaroo')

marshmello = Band.create(name: 'Mashmello')
jack_white = Band.create(name: 'Jack White')
tiesto = Band.create(name: 'Tiesto')
killers = Band.create(name: 'The Killers')
tyler = Band.create(name: 'Tyler The Creator')
